describe('Preview video testing', () => {
  it('visits the app root url', () => {
    cy.viewport('macbook-16')
    cy.visit('/')
    cy.request('https://quwnhu3hf8.execute-api.us-east-2.amazonaws.com/test/video-list')
    cy.screenshot('(preview-video-flow)1-home-view', { capture: 'runner'})
    cy.contains('label', 'Añadir nuevo video')
    cy.get('input#inputAdd').should('have.attr', 'placeholder', 'Añadir')
    cy.get('input.button').should('have.attr', 'value', 'Añadir')
    cy.get('#EqWfZspNY3c-card').click()
    cy.screenshot('(preview-video-flow)2-click-card', { capture: 'runner'})
    cy.get('.modal').screenshot('(preview-video-flow)3-preview-modal', { capture: 'runner'})
    cy.get('#preview-title').should('not.be.empty')
    cy.get('#preview-description').should('not.be.empty')
    cy.get('.video-preview').find('iframe')
      .should('have.attr', 'src', 'https://www.youtube.com/embed/EqWfZspNY3c')
    cy.get('.video-preview').find('iframe').document().get('body div').first().click()
      cy.wait(7000)
    // cy.get('.close-modal').click()
  })
})
